# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ('placement',)},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ('placement',)},
        ),
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
