# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20170112_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accordion',
            name='content',
        ),
        migrations.AddField(
            model_name='accordion',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='textblock',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
