# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20170113_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='placement',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
