# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20170113_1458'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='block',
            unique_together=set([]),
        ),
    ]
