# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20170113_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='blocktype',
            field=models.CharField(blank=True, choices=[('T', 'Text'), ('A', 'Accordion')], max_length=50),
        ),
    ]
