# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 05:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_page_pagetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Block')),
            ],
            options={
                'abstract': False,
            },
            bases=('pages.block',),
        ),
        migrations.AlterField(
            model_name='block',
            name='blocktype',
            field=models.CharField(blank=True, choices=[('T', 'Text'), ('A', 'Accordion'), ('C', 'Contact')], max_length=50),
        ),
    ]
