# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 02:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20170120_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Block')),
            ],
            options={
                'abstract': False,
            },
            bases=('pages.block',),
        ),
        migrations.CreateModel(
            name='InfoCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='pages.InfoBlock')),
            ],
        ),
        migrations.CreateModel(
            name='InfoContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('templates', models.TextField()),
                ('groups', models.TextField()),
                ('reading', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='pages.InfoCategory')),
            ],
        ),
        migrations.AlterField(
            model_name='block',
            name='blocktype',
            field=models.CharField(blank=True, choices=[('T', 'Text'), ('A', 'Accordion'), ('C', 'Contact'), ('I', 'Info')], max_length=50),
        ),
    ]
