# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_auto_20170227_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkboxblock',
            name='empty_text',
            field=models.TextField(blank=True),
        ),
    ]
