# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 18:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0016_checkboxblock_empty_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='statepage',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='states', to=settings.AUTH_USER_MODEL),
        ),
    ]
