# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='role',
            field=models.CharField(choices=[('A', 'Admin'), ('E', 'Editor')], default='A', max_length=1),
        ),
    ]
